import { SessionProvider } from "next-auth/react";
import Head from 'next/head';


// Context
import NotifyProvider from '../context/NotifyContext';
import CustomThemeProvider from '../context/ThemeContext';

// Components
import Navbar from '../components/Navbar';
import ProgressBar from '../components/ProgressBar';

// MUI Components
import Box from '@mui/material/Box';

// Stylesheets
import '../styles/globals.css';


function MyApp({ Component, pageProps: { session, ...pageProps } }) {
    return (
        <SessionProvider session={session}>
            <CustomThemeProvider>
                <NotifyProvider>

                    <Head>
                        <title>Manage.io</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>

                    <Box sx={{ backgroundColor: 'background.default', minHeight: '100vh' }}>
                        <Navbar />
                        <Component {...pageProps} />

                        <ProgressBar />
                    </Box>

                </NotifyProvider>
            </CustomThemeProvider>
        </SessionProvider>
    )
}

export default MyApp
